name:    wordest-back-end
version: "0.0.0"

dependencies:
- base
- yesod-core
- bytestring-trie
- array
- bytestring

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  wordest-back-end:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordest-back-end

tests:
  wordest-back-end-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wordest-back-end
      - hspec